#!/bin/bash

# Fix the settings.php symbolic links.

# back off settings.php first just to be sure
if [[ -f settings.php ]]
then
  echo "Backing up settings.php"
  cp settings.php settings.backup.php
else
  echo "settings.php file not found!"
  exit 1
fi

echo "Updating manage settings.php"
### Don't forget to delete "./settings.php" from the listing or bad things will happen
SETTINGS=''
SETTINGS="$SETTINGS ./accounts/settings.php"
SETTINGS="$SETTINGS ./bugs/settings.php"
SETTINGS="$SETTINGS ./build/settings.php"
SETTINGS="$SETTINGS ./edit/settings.php"
SETTINGS="$SETTINGS ./faq/settings.php"
SETTINGS="$SETTINGS ./features/settings.php"
SETTINGS="$SETTINGS ./login/settings.php"
SETTINGS="$SETTINGS ./login/functions/settings.php"
SETTINGS="$SETTINGS ./manage/settings.php"
SETTINGS="$SETTINGS ./reports/settings.php"
SETTINGS="$SETTINGS ./show/settings.php"
### Don't forget to delete "./settings.php" from the listing or bad things will happen

# now remove the existing standalone settings file and create symbolic links
for i in $SETTINGS
do
  if [[ ! $i = './settings.php' ]]
  then
    if [[ -f $i ]]
    then
      rm $i
    fi
    ln settings.php $i
  fi
done

echo "Done..."

